services:
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: handy-fe-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_WS_API_URL=http://localhost:8000
      - VITE_AUTHORIZATION_SESSION=HANDY_KEY
      - VITE_BACKEND_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: development
    container_name: handy-be-dev
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/handy
      - JWT_SECRET_KEY=development_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
      - db-network
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migrate:dev && npm run start:dev"
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=handy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data_dev:
  pgadmin_data_dev:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge