# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handy-db 
  namespace: handy
  labels:
    app: handy-db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handy-db 
      tier: database
  template:
    metadata:
      labels:
        app: handy-db 
        tier: database
    spec:
      containers:
        - name: handy-db 
          image: postgres:latest
          ports:
            - protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: handy
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 750Mi
              cpu: 750m
            limits:
              memory: 1Gi
              cpu: 1000m
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: azure-managed-disk

---
# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 4Gi

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: handy-db 
  labels:
    app: handy-db 
spec:
  selector:
    app: handy-db 
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
